---
- name: setup secrets
  hosts: atomichosts

  vars_files:
    - vault.yml
    - vars.yml

  tasks:
    - include: util/kube_ip.yml

    - name: make sure directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items:
        - /var/kubernetes
        - /var/kubernetes/secrets
  
    - name: template out secret files
      template:
        src: templates/secrets.j2
        dest: /var/kubernetes/secrets/{{ item }}.yml
      with_items: "{{ secrets }}"
  
    - name: create gitlab secrets
      kubernetes:
        api_endpoint: "{{ kubernetes_ip }}:{{ kubernetes_port }}"
        #api_endpoint: "localhost:6443"
        url_username: ansible
        file_reference:  /var/kubernetes/secrets/{{ item }}.yml
      with_items: "{{ secrets }}"
      tags: [gitlab]
