---
- name: install postgres container
  hosts: atomichosts

  vars_files:
    - vault.yml
    - vars.yml

  tasks:
    - name: get percona address
      command: /usr/bin/kubectl get ep percona --output=json
      changed_when: false
      register: percona_raw

    - set_fact:
        percona_endpoint: "{{ percona_raw.stdout | from_json }}"

    - set_fact:
        percona_ip: "{{ percona_endpoint.subsets[0].addresses[0].ip }}"

    # TODO may have to run ldconfig as ostree doesn't?

    - name: create percona databases
      mysql_db:
        name: "{{ item }}"
        state: present
        login_host: "{{ percona_ip }}"
        login_user: root
        login_password: "{{ secrets.percona_passwords['root'] }}"
      with_items: "{{ percona_databases }}"

    - name: create percona users
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ secrets.percona_passwords[item.name] }}"
        priv: "{{ item.priv }}"
        state: present
        login_host: "{{ percona_ip }}"
        login_user: root
        login_password: "{{ secrets.percona_passwords['root'] }}"
      with_items: "{{ percona_users }}"
