---
- name: run percona container
  hosts: atomichosts

  vars_files:
    - vault.yml
    - vars.yml

  tasks:
    - name: template percona deployment
      template:
        src: templates/deployments/percona.j2
        dest: /var/kubernetes/deployments/percona.yml
        owner: root
        group: root
        mode: 0644

    - name: create percona deployment
      command: /usr/bin/kubectl create -f /var/kubernetes/deployments/percona.yml
      register: createdeployments
      failed_when: false
      tags: [latest]
      changed_when: false

    - name: expose percona deployment
      command: /usr/bin/kubectl expose deployment percona
      failed_when: false
      tags: [latest]
      changed_when: false

    - name: get percona address
      command: /usr/bin/kubectl get ep percona --output=json
      changed_when: false
      register: percona_raw

    - set_fact:
        percona_endpoint: "{{ percona_raw.stdout | from_json }}"

    - set_fact:
        percona_ip: "{{ percona_endpoint.subsets[0].addresses[0].ip }}"

    # TODO may have to run ldconfig as ostree doesn't?

    - name: create percona databases
      mysql_db:
        name: "{{ item }}"
        state: present
        login_host: "{{ percona_ip }}"
        login_user: root
        login_password: "{{ secrets.percona_passwords['root'] }}"
      with_items: "{{ percona_databases }}"

    - name: create percona users
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ secrets.percona_passwords[item.name] }}"
        priv: "{{ item.priv }}"
        state: present
        login_host: "{{ percona_ip }}"
        login_user: root
        login_password: "{{ secrets.percona_passwords['root'] }}"
      with_items: "{{ percona_users }}"
