---
- name: run certbot container
  hosts: atomichosts

  vars_files:
    - vault.yml
    - vars.yml

  handlers:
    - name: reload frontend
      shell: /usr/bin/kubectl exec $(kubectl get pods -l 'app=frontend' --no-headers -o=custom-columns=NAME:.metadata.name) /reload.sh
      failed_when: false

  tasks:
    - name: template certbot deployment
      template:
        src: templates/deployments/certbot.j2
        dest: /var/kubernetes/deployments/certbot.yml
        owner: root
        group: root
        mode: 0644
      tags: [ certbot ]

    - name: create certbot deployment
      command: /usr/bin/kubectl create -f /var/kubernetes/deployments/certbot.yml
      register: createdeployments
      failed_when: false
      changed_when: false
      tags: [ certbot ]

    - name: expose certbot deployment
      command: /usr/bin/kubectl expose deployment certbot
      failed_when: false
      tags: [latest]
      changed_when: false

    - name: get certbot address
      command: /usr/bin/kubectl get ep certbot --output=json
      changed_when: false
      register: certbot_raw

    - set_fact:
        certbot_endpoint: "{{ certbot_raw.stdout | from_json }}"

    - set_fact:
        certbot_ip: "{{ certbot_endpoint.subsets[0].addresses[0].ip }}"

    - name: make default vhost dir
      file:
        path: /var/frontend/config/vhost.d/default
        state: directory

    - name: template certbot vhost
      template:
        src: templates/certbot-vhost.j2
        dest: /var/frontend/config/vhost.d/default/certbot.conf
      notify:
        - reload frontend

