---
- include: 01-install.yml
- include: 02-customize.yml
- include: 03-firewall.yml
- include: 04-kubernetes.yml
- include: 05-secrets.yml
- include: 06-containers.yml
- include: 07-percona.yml
- include: 07-postgres.yml
- include: 08-frontend.yml
- include: 09-wordpress.yml

